### ISSUE TITLE
[SUGGESTION] Timestamps in /user

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#100]
**Is your feature request related to a problem? Please describe.**
Whenever doing /user, there is no indication to what timezone is being displayed.

**Describe the solution you'd like**
A solution I propose is to simply use Discord's native timestamp formatting. You could simply let it display in whatever timezone the user has.

**Additional context**
![image](https://user-images.githubusercontent.com/44620677/126838219-3c2c19ef-292e-480e-9ec6-e9594fb338d1.jpeg)
(It also hadn't updated to say 5 years despite passing the 5 year point)

![image](https://user-images.githubusercontent.com/44620677/126838227-df184960-242b-4922-ad92-c60385df5b94.jpeg)

**Comment by GamingGeek** [comment]
I'll be switching to timestamps eventually, just not sure when will be a good time to add it since people need to update to see them

**Comment by Aktimoose** [comment]
> since people need to update to see them

Haven't they been available on all platforms for almost a month? I feel like a month is an appropriate amount of time to wait.

**Comment by GamingGeek** [comment]
> > since people need to update to see them
> 
> Haven't they been available on all platforms for almost a month? I feel like a month is an appropriate amount of time to wait.

iOS stable only got them very recently. It also takes quite a bit for a lot of people to update which is why I'm holding off on using them yet

**Comment by Zordlan** [comment]
_its been a month since this suggestion was opened_ ios seems to automatically update for me, idk if ive just got auto updates in the app store enabled or not but i heard somewhere that discord updates independently of the app store

**Comment by GamingGeek** [comment]
This will be added soon
