### ISSUE TITLE
[BUG] You can use fire close in a thread

### ISSUE THREAD

**Issue by Mr-PenguinMan** [FireDiscordBot/bot#101]
Tittle, once u click close nothing happans

 

1. go in thread
2. do fire close

![image](https://user-images.githubusercontent.com/63758798/127403991-9c46a671-8b57-4393-a1bc-993072f7f4b9.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/63758798/127404012-2b9122ac-1489-4fd1-87eb-6d8990d83089.png)

**Comment by GamingGeek** [comment]
this is a hot mess of a bug report

**Comment by GamingGeek** [comment]
Upon further inspection, this behavior is consistent across all channel types and not actually a bug.
