### ISSUE TITLE
[BUG] slashcommands (at least /user) don't work right in private threads

### ISSUE THREAD

**Issue by Zordlan** [FireDiscordBot/bot#102]
**Describe the bug**

slashcommands in private threads (and maybe public ones? haven't tested) don't work if the bot hasn't been invited

**To Reproduce**

make a private thread, run a slashcommand before pinging the bot

**Expected behavior**

i was expecting the slashcommand to run and the bot to join the thread

**Screenshots**

![image](https://user-images.githubusercontent.com/69115669/127421436-99c96abe-37d4-43d2-8c5e-2acfa035c6de.png)

**Discord & device versions**

ubuntu 20.04.2 lts, discord is whatever it uses for browsers

**Additional context**

![image](https://user-images.githubusercontent.com/69115669/127421522-14285d9d-9205-488d-997e-b7a257b93256.png)

**Comment by Zordlan** [comment]
oh also it worked fine after pinging the bot

**Comment by nearlySplat** [comment]
possibly the bot wasn't able to access the channel to send the follow-up, and by pinging it you added it to the thread

**Comment by GamingGeek** [comment]
This is due to some pre-command checks failing since it cannot access the thread due to not being added / not having `Manage Threads`

You should now get an error mentioning this now since 947e7ad
