### ISSUE TITLE
[SUGGESTION] Log server avatar updates

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#104]
**Is your feature request related to a problem? Please describe.**
Server avatar updates are not logged in audit logs.

**Describe the solution you'd like**
For them to be logged in moderation logs.

**Additional context**
![image](https://user-images.githubusercontent.com/44620677/128620148-660a4d6c-c992-4299-844b-8f772ffb6f38.jpeg)
![image](https://user-images.githubusercontent.com/44620677/128620150-76023c39-8066-4da7-8001-ac5da9025966.jpeg)
![image](https://user-images.githubusercontent.com/44620677/128620153-88a17285-bf72-405f-bc21-fd021cad0265.jpeg)

**Comment by Zordlan** [comment]
this is in theory a good idea but it would be hell in bigger servers, maybe a new "user" logs category for this stuff?

**Comment by Aktimoose** [comment]
> this is in theory a good idea but it would be hell in bigger servers, maybe a new "user" logs category for this stuff?

i suggested moderation logs because nickname changes are already logged

**Comment by Zordlan** [comment]
oh wait, server avatar, i thought you meant normal avatar lmao

**Comment by GamingGeek** [comment]
oh yeah forgot I needed to respond to this lol

avatar logs won't be a thing, neither global nor server
