### ISSUE TITLE
[SUGGESTION] Command fire australia it flips your pfp

### ISSUE THREAD

**Issue by L1lBabyyy** [FireDiscordBot/bot#105]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by GamingGeek** [comment]
Oops, forgot to respond to this earlier!

All image generation commands are done using external APIs and I do not plan on adding any local image generation to Fire.
Since I am unaware of any APIs that have this functionality, I'm unable to implement it in Fire.
