### ISSUE TITLE
[SUGGESTION] Add more pride avatar commands

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#106]
**Is your feature request related to a problem? Please describe.**
trans circle looks mad ugly with that gradient and i have a server full of people who agree

**Describe the solution you'd like**
make the /trans command not have an ugly gradient just use the normal trans pride flag with solid lines

**Additional context**
i'm also not trans myself can you add a gay rainbow one 🥺 (also if there's too much bloat with these you could put it all in /pride [type] [user])

**Comment by Aktimoose** [comment]
sorry for the informality i was uhhh idk

**Comment by GamingGeek** [comment]
The trans command uses an external API to generate the images therefore I personally cannot change the design of it.

As for adding more commands, it is on my list of things to do, it's just not a high priority though I will bump it up.

**Comment by GamingGeek** [comment]
Closed by e0223655535900a4e8b5ac8ea4f8ce779b173007
