### ISSUE TITLE
[SUGGESTION] make modlogs have user id in footer

### ISSUE THREAD

**Issue by Zordlan** [FireDiscordBot/bot#108]
**Is your feature request related to a problem? Please describe.**
When you run `/modlogs` (as a slash command) there isn't a way to copy the user's id
![image](https://user-images.githubusercontent.com/69115669/130310355-ab93d6de-fa5b-4518-a325-605ee19ef203.png)

**Describe the solution you'd like**
just putting the user id in the footer, if possible, quite a few other commands/features have that

**Describe alternatives you've considered**
getting discord to let you copy user id in slashcommand args idk

**Additional context**
not much other than nopo wanting the user id for some reason in mb #evidence

**Comment by GamingGeek** [comment]
Will be added soon.
