### ISSUE TITLE
[SUGGESTION] Improve ban / mute messages.

### ISSUE THREAD

**Issue by xiUnknown1** [FireDiscordBot/bot#111]
Fire should tell you for how long you have been muted / banned for. 

Also another suggestion is to make being able to temporarily ban people possible.

**Comment by GamingGeek** [comment]
> Fire should tell you for how long you have been muted / banned for.
No.

> Also another suggestion is to make being able to temporarily ban people possible.
Already possible, just include a time like you would in the mute command
