### ISSUE TITLE
[BUG] Moderation slash commands don’t produce output

### ISSUE THREAD

**Issue by ghost** [FireDiscordBot/bot#115]
**Describe the bug**

When using a moderation command such as `/warn` or `/mute` the command runs successfully but does not send any output to the channel to command was used in.

**To Reproduce**

Use any moderation command. For example `/warn`

**Expected behavior**

An embed is sent to the invocation channel confirming the moderation action.

**Discord & device versions**

App: 94.0 (28267) stable; Manifest: W/"867744694017f75631f4d3c8b4183d22"; Build Override: N/A; Device: iPhone13,4 OS 15.0;

**Comment by GamingGeek** [comment]
Fixed on branch feature/better-slash-commands which is usable on [Fire Beta](https://inv.wtf/betabot)

It is unknown when this will be merged as it is a major overhaul of slash command handling and requires a lot of testing
