### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Feel65** [FireDiscordBot/bot#120]
The problem that’s recently plagued hundreds of thousands of Discord users and servers, scam links that contain the ability to repost themselves infinitely, are a menace that need to be stopped.

Now, with Fire,  a scamlink blocker could be implemented, running off of a database potentially such as the one found in[this database](https://github.com/nacrt/SkyblockClient-REPO/blob/main/files/scamlinks.json)  for @Lisenaaaa’s Rain-TEMP bot, that does the following:

1: Blacklisted link is sent
2: Fire detects said blacklisted link
3: Fire deletes message(s) containing blacklisted link
4: Fire does one of the following, based on user configuration by /spamlink 
    4a: Temporarily mute member who sent the link, default time is 15 minutes but can be changed in /spamlink mutetime 
    4b: Temporarily ban the member who sent the link, default time is again 15 minutes but user-configurable via /spamlink bantime
    4c: Permanently ban the user who sent the link, enabled by setting /spamlink bantime to 0
    
Some alternative bots that already do this (that I know of) include @Lisenaaaa’s Rain-TEMP bot. That’s all

I don’t really have a context screenshot, but just look around discord DMs and whatnot. You’ll find a “Free nitro at deezcord.gg/nuts” link somewhere

**Comment by GamingGeek** [comment]
Closing this as it's not going to happen any time in the near future
