### ISSUE TITLE
[SUGGESTION] Rolestate

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#123]
**Is your feature request related to a problem? Please describe.**
A rolestate function that gives people back their roles when they leave and come back

**Describe the solution you'd like**
Logs the roles and nickname a user has before they leave the server/get banned and give it back when they come back

**Describe alternatives you've considered**
The 42 bot has this feature, but it often has very out of date roles and nicknames, sometimes even being over a year old.

**Additional context**
Could use the same logged roles and nickname from the moderation logs.
![image](https://user-images.githubusercontent.com/44620677/140419247-13ae55fc-74e4-417e-80d4-b6d595dd7ba0.png)

**Comment by GamingGeek** [comment]
I don't think this will be added as it'd require storing a ton of data and updating that data a bunch.

It would also suffer from the same issue as Fire doesn't always have members cached so it won't always know what roles they had.
