### ISSUE TITLE
[SUGGESTION] Ticket transcripts and Logs

### ISSUE THREAD

**Issue by EthanDevelops** [FireDiscordBot/bot#124]
**Is your feature request related to a problem? Please describe.**
Not really.

**Describe the solution you'd like**
I would like there to be a setting where Fire automatically logs and transcripts tickets after you close them (possibly in hastebin)

**Describe alternatives you've considered**
Fire transcripts logs and sends them to the creator of the log but it would be nice if Fire also gave an option to save the ticket transcript in the Ticket category.

**Additional context**

**Comment by GamingGeek** [comment]
Fire already sends transcripts to your action logs channel
