### ISSUE TITLE
[BUG] /ticket alert not working

### ISSUE THREAD

**Issue by EthanDevelops** [FireDiscordBot/bot#125]
When I use /ticket alert with a role to alert when someone makes a ticket, it doesn’t alert that role.

 

1. Setup tickets with /ticket fire
2. Run /ticket alert and pass a role as a parameter
3. Run /new and it doesn’t ping the role specified in /ticket alert

The role specified in /ticket alert to be alerted / pinged when someone creates a new ticket.

**Screenshots**

**Discord & device versions**
* Discord 99.0, iPad, iOS 15.1

**Additional context**

**Comment by GamingGeek** [comment]
I first tried to reproduce this and succeeded, added the work in progress label and then went to investigate.

I then remembered that moderators opening tickets doesn't ping the alert role, which is likely the case here. 
@EthanDevelops does it ping if a non-moderator opens a ticket?

**Comment by EthanDevelops** [comment]
It does :D thanks
