### ISSUE TITLE
[SUGGESTION] Discord Activity command

### ISSUE THREAD

**Issue by EthanDevelops** [FireDiscordBot/bot#126]
**Is your feature request related to a problem? Please describe.**
Nope :D

**Describe the solution you'd like**
An activity command that allows you to play a discord activity (YouTube Together, Fishington.io, etc.) in a voice channel

**Describe alternatives you've considered**
I have a bot that does this but it would be nice if it was in Fire.

**Additional context**
![D4B444EB-F1E6-4F04-9DEF-95E9D7E92BD5](https://user-images.githubusercontent.com/66741050/141657043-ccc8ee40-8f2e-40fb-adaa-0653d56ab7a8.jpeg)

**Comment by EthanDevelops** [comment]
You could map all the activities like:
```typescript
        'Poker Night': '755827207812677713',
	'Betrayal.io': '773336526917861400',
	'Fishington.io': '814288819477020702',
	'YouTube Together': '755600276941176913',
	'Chess in the Park': '832012774040141894',
	'Watch Together': '880218394199220334',
	'Doodle Crew': '878067389634314250',
	'Wood Snacks': '879863976006127627',
	'Letter Tile': '879863686565621790' 
```
And then create an invite like this:
```typescript
                 await (client as any).api
			.channels(channel.id)
			.invites.post({
				data: {
					validate: null,
					max_age: 10000,
					max_uses: 0,
					target_type: 2,
					the id of the activity (from the map),
					temporary: false
				}
			})
```

**Comment by EthanDevelops** [comment]
(from): https://github.com/NotEnoughUpdates/bush-bot/blob/master/src/commands/utilities/activity.ts

**Comment by GamingGeek** [comment]
Not going to add this as it's be taking the sole feature of [advaith's activities bot](https://s.advaith.io/activities) and Discord have said they aren't verifying any more bots with this feature so it's probably not a good idea to add it anyways.
