### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by ThatAwkwardGithub** [FireDiscordBot/bot#128]
Random characters for badnames? Make it so we can create our own custom badname but with random characters. You can add like a {random(interval)} plugin to the /badname command.
Ex: /badname Moderated Nickname {random8}
Preview: Moderated Nickname (XXXXXXXX)

**Comment by GamingGeek** [comment]
This won't be added. If you want a randomized element, keep the default `John Doe XXXX` where `XXXX` is replaced with the user's discriminator
