### ISSUE TITLE
[SUGGESTION] Sapphire Migration

### ISSUE THREAD

**Issue by BrianWasTaken** [FireDiscordBot/bot#130]
**Is your feature request related to a problem? Please describe.**
Yes but no.

**Describe the solution you'd like**
Akairo hasn't done any major updates for so long (I love akairo) but it would be good to try something new. [Sapphire](https://npmjs.com/package/@sapphire/framework) framework is just so op.

**Describe alternatives you've considered**
Stay in akairo.

**Additional context**
None because I'm like begging the fire devs to rewrite a f*ck ton of areas on their bot just to migrate to something lol.

**Comment by Lisenaaaa** [comment]
there's only one person working on fire

**Comment by GamingGeek** [comment]
I don't think I'll be changing from Akairo any time soon
