### ISSUE TITLE
[SUGGESTION] Use Crowdin's new "open-source project" beta feature for localization.

### ISSUE THREAD

**Issue by Deftu** [FireDiscordBot/bot#137]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The use of Crowdin's open-source project translation feature would be nice for easier translations, I believe it's free from what I've read.

**Describe alternatives you've considered**
None found.

**Additional context**
Crowdin added an option to make translation projects for open-source projects, and from what I've seen it's free.

**Comment by GamingGeek** [comment]
I was already using crowdin until they suspended my project. I haven't had a chance to contact them about it so until then, this will be on hold.

**Comment by Deftu** [comment]
@GamingGeek the open-source project feature is unrelated to a plan or project, it's a free project without needing a plan on your account.

**Comment by GamingGeek** [comment]
@Deftu The project should be unsuspended now, could you verify this on your end? https://inv.wtf/i18n

**Comment by Deftu** [comment]
> @Deftu The project should be unsuspended now, could you verify this on your end? https://inv.wtf/i18n

Yep, looks unsuspended on my end. I'll be sure to contribute some translations soon enough.
