### ISSUE TITLE
[BUG] When using Hytilities Reborn with the Log Scanner, it thinks it’s normal hytilities. 

### ISSUE THREAD

**Issue by EthanDevelops** [FireDiscordBot/bot#138]
**Describe the bug**
When uploading a log using Fire’s log scanning feature, if you are using [Hytilities Reborn](https://github.com/W-OVERFLOW/Hytilities-Reborn) with the classpath net.wyvest.hytilities, Fire thinks that you are using normal Hytilities, and displays the error message:
- Hytilities is no longer supported and may break at any time due to changes made by Hypixel, use at your own risk

**To Reproduce**
Use Hytilities Reborn, and upload an error log.

**Expected behavior**
No message shown.

**Screenshots**
N/A

**Discord & device versions**

App: 106.0 (Build 29538) stable; Build Override: N/A; Device: iPad13,4 OS 15.2;

**Additional context**
N/A

**Comment by GamingGeek** [comment]
This is somewhat intentional. Hytilities Reborn is not recommended/endorsed by Sk1er LLC and we cannot rely on the fork being continued so it is better to have it trigger even on forks
