### ISSUE TITLE
[SUGGESTION] Ternary conditional operators for features like the welcome/leave messages.

### ISSUE THREAD

**Issue by Deftu** [FireDiscordBot/bot#141]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
A ternary operator-like option for such as the welcome/leave messages (can be used to display whether a user was banned or not)

**Describe alternatives you've considered**
Potentially add an option for default text for bans and kicks in welcome/leave messages ("[This user was banned]" | "[This user was kicked]")

**Additional context**
This could be a good option for powerusers and can be useful for other features in the future.

**Comment by GamingGeek** [comment]
The join & leave messages are meant to be friendly welcome/goodbye messages, not calling out someone who was kicked or banned.

If you want to know if they were kicked/banned, use member logs
