### ISSUE TITLE
[SUGGESTION] Allow adding only top or bottom text to the makeameme slash command

### ISSUE THREAD

**Issue by Moire9** [FireDiscordBot/bot#146]
**Is your feature request related to a problem? Please describe.**
Not all functionality of the original makeameme command is present in the /makeameme slash command, however the original one doesn't work. Notably, you cannot add text to only the top or bottom, you must add it to both.

**Describe the solution you'd like**
Making the `top` and `bottom` command arguments optional so that text can be added to only the top or bottom.

**Describe alternatives you've considered**
Allowing the original command to be used works too.

**Additional context**
![image](https://user-images.githubusercontent.com/31591796/153808209-94b5a63b-b70e-4da4-a447-e2147aaa4c24.png)

**Comment by Moire9** [comment]
I didn't even have the image in my clipboard anymore but I didn't notice :|

**Comment by Moire9** [comment]
@GamingGeek providing no value for one of the commands uses `null`, instead of `""`.  
![image](https://user-images.githubusercontent.com/31591796/154178972-b310af53-b09a-4dd3-bef7-76a5f5af4fc4.png)

**Comment by GamingGeek** [comment]
> @GamingGeek providing no value for one of the commands uses `null`, instead of `""`. ![image](https://user-images.githubusercontent.com/31591796/154178972-b310af53-b09a-4dd3-bef7-76a5f5af4fc4.png)

Fixed
