### ISSUE TITLE
[BUG] Quoting system messages provides unexpected results

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#147]
**Describe the bug**

Quoting the indicator of a thread's creation treats it like a normal message.

**To Reproduce**

- Copy message link of a message of the creation of a thread
- Quote it

**Expected behavior**

A similar thing to the embed when you quote a join message or any other system message.

**Screenshots**

![image](https://user-images.githubusercontent.com/44620677/155901854-4f782d4e-1818-4534-9737-977324afa5b7.jpeg)

The message in question
![image](https://user-images.githubusercontent.com/44620677/155901857-48bcd959-1520-485b-8929-61b4448213b8.jpeg)

**Comment by GamingGeek** [comment]
I plan to make it quote all system messages the same way it'd appear in the client, including the thread create message
