### ISSUE TITLE
[SUGGESTION] Use the built-in Command Permissions v2

### ISSUE THREAD

**Issue by SuperchupuDev** [FireDiscordBot/bot#150]
**Is your feature request related to a problem? Please describe.**
Discord has recently released perms v2 for commands, it would be really cool if Fire used them instead of the current system it has
https://discord.com/blog/slash-commands-permissions-discord-apps-bots

**Describe the solution you'd like**
Implement permissions v2

**Describe alternatives you've considered**
none

**Additional context**
Perms v2 are a really great UX for both users and admins, it would be great if Fire used them

**Comment by GamingGeek** [comment]
What exactly would you be looking for in an integration with perms v2? I haven't figured out the extent of what I'm going to do with it yet so I'd like to hear what people want

**Comment by SuperchupuDev** [comment]
Based on what I've heard of the current system the bot uses (I haven't used that system myself) you can add users as moderators via some command so they can use moderation commands, which are locked with Manage Guilds by default.

I think perms v2 can easily replace this system since administrators of the guild can allow access of any command they want to certain roles/users via the Integrations tab, while also providing a default set of permissions added by the developer, which is pretty much what Fire already does, but with better UX (commands are hidden if you don't have perms to use it, etc)
