### ISSUE TITLE
[SUGGESTION] "purge-until" command

### ISSUE THREAD

**Issue by Moire9** [FireDiscordBot/bot#153]
Sometimes, you want to purge messages, but you don't want to count up the number to purge. What about the ability to purge up to a certain message, provided as either a message ID or a message link. That way, you just scroll up to the final message you want deleted, and then purge everything up to and including that message. Would make it a lot easier.

**Comment by Smidul** [comment]
It would be nice to also have a message command (context menu) for it, deleting all messages starting with or after the selected message

> Example with AdvaithBot:
![image](https://user-images.githubusercontent.com/45880040/168693944-23179bee-d5b7-4b64-940f-60d408a52cb9.png)

**Comment by Moire9** [comment]
Oh yeah, I forgot that bots could do context menus. Yeah that would arguably be better.

**Comment by Moire9** [comment]
IDK if it will sway your opinion but I find myself counting messages to purge a lot, and wouldn't be surprised if a lot of server owners agree.  On Thu, Sep 8, 2022 at 14:37, Jake Ward ***@***.***> wrote:  
Closed #153 as not planned.
