### ISSUE TITLE
[SUGGESTION] Use MLM flag for pride command.

### ISSUE THREAD

**Issue by Deftu** [FireDiscordBot/bot#154]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
The pride command seems to use the LGBTQ flag instead of the MLM flag for the "gay" option.

**Describe alternatives you've considered**
N/A

**Comment by GamingGeek** [comment]
This command uses an external API that I have no control over so I am unable to change or add flags
