### ISSUE TITLE
[SUGGESTION] Fire Channel Following

### ISSUE THREAD

**Issue by Maximusbarcz** [FireDiscordBot/bot#155]
**Describe the solution you'd like**
A ability to follow Channels in Servers with the fire bot Similar to the default feature but not limited to 10 channels.

**Comment by GamingGeek** [comment]
This is not something I will be adding to Fire as it is already a feature in Discord and has much better UX than what I could do with Fire. The 10 webhooks per channel limit is annoying and I recommend giving Discord your feedback on that
