### ISSUE TITLE
Discord Auto Mod

### ISSUE THREAD

**Issue by TruckRiderRBLX** [FireDiscordBot/bot#157]
**Is your feature request related to a problem? Please describe.**
No, addon suggestion.

**Describe the solution you'd like**
A basic automod for preventing raids and advertising in unwanted channels. This would make Fire a 100% amazing moderation bot to keep in my server instead of having two because the other one has automod and Fire doesn't

**Describe alternatives you've considered**
Auttaja and Dyno.

**Comment by GamingGeek** [comment]
With the addition of Discord's native automod, Fire will not be getting a full fledged automod feature

For raid prevention, I recommend using [Beemo](https://beemo.gg/), though it may eventually be replaced by better native raid prevention as the original developer works for Discord now.

As for advertising, Fire currently has a couple link filters which you can find with the `/linkfilter` commands and this will be expanded in the future

If you have any suggestions for additions to the link filter selection, you can let me know here
