### ISSUE TITLE
[BUG] Fire doesn't send the message for reminders

### ISSUE THREAD

**Issue by Czekoloczek** [FireDiscordBot/bot#167]
If you create a reminder and then wait for the reminder to remind you, it doesn't do that.

 

**Steps to reproduce:**
- Create a reminder (I recommend 2 minutes since it's the shortest)
- Wait for the time that you set up for the reminder

**Expected behaviour:**
The bot should send a message to you (remind you)

**Screenshots:**
![image](https://github.com/FireDiscordBot/bot/assets/76474182/64c5495c-c8bf-43e3-8ad3-b19e225bb787)

**Discord & device versions**

canary 295016 (bd8df0b) Host 1.0.356 x64 (48014) Windows 11 64-bit (10.0.22631)
Vencord dac2d75 (Standalone)
Electron 30.0.5
Chromium 124.0.6367.207

**Comment by GamingGeek** [comment]
Do you have DMs enabled in a server that you share with Fire or have you added it as a User App?

**Comment by Czekoloczek** [comment]
Yes i have added it as a user App

**Comment by Czekoloczek** [comment]
I worked fine like 3 days ago

**Comment by Czekoloczek** [comment]
I think it stopped working on 18-19 May

**Comment by GamingGeek** [comment]
I've looked into this and Fire was hit with a 403 when it tried to send the message to you.

I've added some checks to ensure the User App is installed when running the command & additional logging for when the request fails. Could you try again? @Czekoloczek

**Comment by Czekoloczek** [comment]
works now
