### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by pvishalkeerthan** [FireDiscordBot/bot#173]
@GamingGeek 
Would like to add hover effects and improve styling of cards

![Screenshot 2024-10-08 014037](https://github.com/user-attachments/assets/4e08f118-b066-4d7e-a6dc-92b68f53c089)

**Comment by GamingGeek** [comment]
This repository is for the bot itself, not the website. You can find the website on [FireDiscordBot/website](https://github.com/FireDiscordBot/website/tree/2.x)
