### ISSUE TITLE
/logging doesn't work

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#49]
![image](https://user-images.githubusercontent.com/44620677/106707257-ed0a5100-65be-11eb-8e33-75f300b03f72.jpeg)
Whenever I select the members logging type when using the slash command, it will say it's not a valid logging type. The same thing happens with the other 2 types. 
![image](https://user-images.githubusercontent.com/44620677/106707268-f0054180-65be-11eb-946b-c7599650d9cf.jpeg)

**Comment by TymanWasTaken** [comment]
https://discord.com/channels/564052798044504084/564067823014641664/806197069718224917

It has been fixed in a7b727f (I think), but maybe not the main bot yet

**Comment by GamingGeek** [comment]
bruh this literally worked in the dev bot

**Comment by GamingGeek** [comment]
Turns out the issue was arguments being out of order and since I only tested `/logging Moderation`, the arguments were in order since there was only one hence why it worked in the dev bot
