### ISSUE TITLE
Incorrect log when disabling welcome screen

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#52]
When disabling the welcome screen for a server, the logs will say that a removed feature was "Welcome Screen Enabled", instead of saying that the removed feature was the "Welcome Screen". Same goes for enabling the welcome screen.

![image](https://user-images.githubusercontent.com/44620677/107877334-a7555e80-6ec3-11eb-98ce-063612a82b2a.png)

**Comment by GamingGeek** [comment]
The feature name is `WELCOME_SCREEN_ENABLED` hence why it says `Welcome Screen Enabled` so it is technically correct
