### ISSUE TITLE
[BUG] Emojis don't display in slash commands

### ISSUE THREAD

**Issue by edazpotato** [FireDiscordBot/bot#67]
**Describe the bug**
 
When you use a slash command that has a success or error message, the emoji does not appear you just see :emojiname:.

**To Reproduce**

Use a slash command like `/public`

**Expected behavior**

The emojis should appear like they do in normal commands.

**Screenshots**

![image](https://user-images.githubusercontent.com/46797041/116031619-27612700-a6b2-11eb-9251-346e7d2df4fa.png)

**Discord & device versions**

* Windows 10 OS Version 2004 (Build 19041.928)
* Stable 83040 (f19e353)

**Additional context**

**Comment by GamingGeek** [comment]
This isn't a bug, you need to enable the `Use External Emojis` permission for the `@everyone` role for webhooks and therefore slash commands to use emojis
