### ISSUE TITLE
[SUGGESTION] Allow clearing more than warns

### ISSUE THREAD

**Issue by D44dalus** [FireDiscordBot/bot#69]
**Is your feature request related to a problem? Please describe.**
I need to clear some mutes & am unable to do so.

**Describe the solution you'd like**
I'd like a command similar to clearwarnings but for mutes & tempbans

**Describe alternatives you've considered**
Allowing clearwarnings to clear modlogs  would also do suffice what I need to happen

**Additional context**

**Comment by GamingGeek** [comment]
I'm not sure on whether I'll be adding this...

Warns without the entry in modlogs is just a DM whereas mutes/bans/kicks have actual consequence therefore I don't think I'll be adding the ability to clear the entries in modlogs but I haven't come to a concrete decision yet.

Closing this as I'm aware of it and will comment on here / edit this comment when I decide on it
