### ISSUE TITLE
[SUGGESTION] Improve Error Messages

### ISSUE THREAD

**Issue by Zordlan** [FireDiscordBot/bot#70]
**Is your feature request related to a problem? Please describe.**
fire's error messages aren't the best tbh

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/69115669/117221105-73505200-adbd-11eb-8934-f24d5c0c16fa.png)
if the user isn't on the server, make it say something like "That user isn't on the server!"

**Describe alternatives you've considered**
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Additional context**

**Comment by GamingGeek** [comment]
the way commands that require a member work doesn't allow me to tell if it's a valid user or not, it just returns null so I can't make it say something like "That user isn't on the server!"

also please set a title before opening an issue and don't just spam "uhhhhhhhhhhh" in the alternatives section

**Comment by Zordlan** [comment]
huh, makes sense

also my brain stops functioning properly later in the day so if im stupid then thats why

couldn't you check if they are on the server, before doing any of the mute code?

**Comment by GamingGeek** [comment]
> it just returns null
