### ISSUE TITLE
Unit conversion command [SUGGESTION]

### ISSUE THREAD

**Issue by Baileymin** [FireDiscordBot/bot#72]
Overview: I'd like a unit conversions commands please 

Explanation: Make a command that's like "fire convert 300ml l" and it returns "0.3L"

Alternatives: None, I would never consider anything outside of Best Bot (and google but that's inconvenient when I just want quick conversion when I'm on Discord)

Additional notes: Maybe just a calculator command in general but not as much

**Comment by GamingGeek** [comment]
I don't think I'll be adding a specific unit conversion command but akin to your alternative, you can use the `$google` command for both conversion and calculation
