### ISSUE TITLE
[SUGGESTION] ttt as alias for tictactoe

### ISSUE THREAD

**Issue by riohorealhk** [FireDiscordBot/bot#76]
**Is your feature request related to a problem? Please describe.**
Typing tictactoe for a command is kinda long and inconvenient 
**Describe the solution you'd like**
Add ttt as an an alias 

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by GamingGeek** [comment]
honestly it probably would've been easier for you to make a pr with it but sure lol
