### ISSUE TITLE
[SUGGESTION] make $reminders have a thing in the embed's footer saying "use $delremind {number} to delete that reminder"

### ISSUE THREAD

**Issue by Zordlan** [FireDiscordBot/bot#87]
**Is your feature request related to a problem? Please describe.**
not really a problem, just $reminders just being a bit unclear

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/69115669/121765710-bbbc0780-cb01-11eb-8dab-f06e915cb6c2.png)

**Describe alternatives you've considered**
honestly im not really sure what a good alternative would be, its already in $help

**Additional context**
what do i put here, other than that i was trying to delete a joke reminder and couldnt figure out how (yes i am both stupid and blind and forgot to look at $help, and when i did while writing this it took me a few minutes to find $delremind)

**Comment by GamingGeek** [comment]
![image](https://user-images.githubusercontent.com/29981918/121765771-5db11380-cb45-11eb-8c1e-528c8a272953.png)
lmfao

also I think I added this in the py version but didn't in the rewrite. will add it in the next big update

**Comment by Zordlan** [comment]
i was planning on learning TS then making a custom command handler once djs v13 came out but they said it would come out this month so fuck that plan lol

**Comment by GamingGeek** [comment]
added in 1a28d633ad83962a282e935db28d3c4de0cceb77
